Overlay changes
overlay-market/merkle-airdrop pull request #1
Opened 2023-10-26 19:35 UTC by EperezOk

2023-11-10 14:16 UTC, TomasCImach requested changes
Is it possible to move the commits of the list generation to another branch/PR?

2023-11-10 14:16 UTC, TomasCImach commented on contracts/src/MerkleClaimERC20.sol
> +        if (amount > token.balanceOf(address(this))) revert NotEnoughRewards();
This wouldn't be neccessary, in this case the tx will revert when `token.transfer(to,amount)` is called.

2023-11-10 14:16 UTC, TomasCImach commented on contracts/src/OverlayV1Token.sol
> +    function unlockTransfers() external onlyRole(DEFAULT_ADMIN_ROLE) {
revert to previous ovl token version with no transfer locks

2023-11-10 14:16 UTC, TomasCImach commented on contracts/src/test/utils/MerkleClaimERC20Test.sol
> +        deal(address(ovl), address(TOKEN), 100e18); // total amount of tokens to be claimed
Setup by transfer the token to the SC, as it'll be done when deployed.

```suggestion
        deal(address(this), address(TOKEN), 100e18); // total amount of tokens to be claimed
        TOKEN.transfer(address(ovl), 100e18);
```

2023-11-10 14:16 UTC, TomasCImach commented on contracts/src/test/utils/MerkleClaimERC20Test.sol
> +        TOKEN = new MerkleClaimERC20(
Change variable name, as this is no longer a token.

2023-11-10 14:16 UTC, TomasCImach commented on generator/.prettierrc.json
Refrain from altering formats within the same pull request where primary changes are made.

2023-11-10 15:23 UTC, EperezOk commented on contracts/src/MerkleClaimERC20.sol
> +        if (amount > token.balanceOf(address(this))) revert NotEnoughRewards();
I borrowed it from the [Frax finance implementation](https://github.com/FraxFinance/merkle-airdrop-starter/blob/master/contracts/src/MerkleClaim.sol#L80-L81), but we can remove it

2023-11-11 00:36 UTC, EperezOk commented
Changes in this PR will be split into #2 and #3.

2023-11-11 00:36 UTC, closed without merging